spring.application.name=provapratica
spring.datasource.url=jdbc:postgresql://localhost:5432/provapratica
spring.datasource.username=postgres
spring.datasource.password=02072002
spring.jpa.hibernate.ddl-auto=update